### ISSUE TITLE
Using a speed instead of scale.

### ISSUE THREAD

**Issue by inerds** [geosenna/simpleParallax#1]
Right now scale factor is being used as speed of transformation as-well right? 

I am in a situation where i donot want any scaling on the image and just wants its parallax movement (translate X / Y).
Is there any way to achieve this ?

**Comment by geosenna** [comment]
This is a pertinent point.

However, the main idea of this plugin is to have a simple parallax effect apply directly on image tags without breaking the layout.

In order to do so, the image scale gives "extra" image matter comparing to its initial size in the viewport. I calculate the range from this extra space and the image can translate between its min and max range.

So the position are actually set automatically to have an image translating and never going out of its original flow in the viewport.

I hope I make myself clear... I'll try to add a schema later to explain how this plugin is working.

**Comment by inerds** [comment]
@geosenna thanks for clearing out your goal of the plugin. I have managed to modify the plugin to suit my requirement of translating only.

Look forward to see more updates of this project

Cheers !

**Comment by drstrangelovesg** [comment]
Hi @inerds mind sharing how you manage to change from scaling to just translating only?

thanks
