### ISSUE TITLE
When multiple images initialized only works when first one is in viewport

### ISSUE THREAD

**Issue by Armadur** [geosenna/simpleParallax#7]
Hello, i have tried your plugin and there is no way i could set it up to work with multiple images...

Structure goes like this

```
text
1) image

text
2) image

text
3) image

text
4) image

text
5) image

```

Next thing is, i have included your script for parallax and i have elements that have id's with this structure id="_1", id="_2", id="_3", id="_4", id="_5"

so, i don't want to initialize 5 times so i did it with for loop.

```
let parallaxElemes = document.getElementsByClassName("parallax-thumbnail").length;
for(let i = 1; i <= parallaxElemes; i++){
        // console.log(jQuery("#_" + i)); // Working as it should be
        jQuery("#_" + i).simpleParallax({
            'orientation': 'down'
        });
}
```

It works on every image but only when first image is in viewport..

Is there quick solution for problem or i just didn't use script as it should be used? 

Thanks in advance

**Comment by geosenna** [comment]
Hi Armadur,

If you plan to use the same settings for all your instance of simpleParallax, I would strongly recommend you to use a global class so you initialize the plugin only 1 time instead of 5 times..

Then for the viewport issue, I am not sure. Are you using the last version 3.1.3? Because some similar issues were appearing in the past and have been fixed.
